---
- hosts: localhost
  gather_facts: no
  vars_files:
  - ./secret_vars.yml
  tasks:
  - hashivault_write: 
      secret: '/my-ca/issue/default'
      data:
         common_name: '{{ cn }}'
         ttl: "17520h"
    register: certs

  - file: path=certs state=directory

  - copy: dest=certs/{{ item.0 }} content={{ item.1 }}
    with_together: 
       - [ "{{ cn }}.pem", "{{ cn }}-key.pem" ]
       - [ "{{ certs.data.data.certificate }}", "{{ certs.data.data.private_key }}" ] 

  - name: Storing secrets in valut 
    hashivault_write: 
       secret: "{{ vault_path }}/config"
       data: "{{ config }}" 

  - hashivault_write: 
       secret: "{{ vault_path }}/certs"
       data: "{{ certs.data.data }}"
